name: Portfolio CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint
        run: htmlhint "**/*.html"

  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: lint  # Only run if lint passes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensures deployment token works

      # Optional: Cache npm dependencies (for future projects)
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build site (static files)
        run: |
          mkdir -p public
          cp -r index.html style.css script.js public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
